var mockMenuData = [{
	"id": 7000,
	"parentId": -1,
	"children": [{
		"id": 7100,
		"parentId": 7000,
		"children": [],
		"icon": "jh icon-jh-department",
		"name": "员工列表",
		"spread": false,
		"path": "page",
		"component": "views/organization/staff/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "员工列表",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 7001,
		"parentId": 7000,
		"children": [],
		"icon": "jh icon-jh-tianjialianxiren",
		"name": "员工新增",
		"spread": false,
		"path": "addUser",
		"component": "views/organization/add/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "员工新增",
		"sort": 2,
		"dataFlag": false
	}],
	"icon": "jh icon-jh-department",
	"name": "组织管理",
	"spread": false,
	"path": "/user",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "组织管理",
	"sort": 7,
	"dataFlag": false
}, {
	"id": 8000,
	"parentId": -1,
	"children": [{
		"id": 8100,
		"parentId": 8000,
		"children": [],
		"icon": "jh icon-jh-kehuxinxi",
		"name": "意向客户列表",
		"spread": false,
		"path": "page",
		"component": "views/intention-customer/info/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "意向客户列表",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 8001,
		"parentId": 8000,
		"children": [],
		"icon": "jh icon-jh-tianjialianxiren",
		"name": "新增意向客户",
		"spread": false,
		"path": "addIntentionCustomer",
		"component": "views/intention-customer/add/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "新增意向客户",
		"sort": 2,
		"dataFlag": false
	}],
	"icon": "jh icon-jh-zu",
	"name": "意向客户",
	"spread": false,
	"path": "/intentioncustomer",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "意向客户",
	"sort": 8,
	"dataFlag": false
}, {
	"id": 9000,
	"parentId": -1,
	"children": [{
		"id": 9100,
		"parentId": 9000,
		"children": [],
		"icon": "jh icon-jh-kehuguanli ",
		"name": "客户列表",
		"spread": false,
		"path": "page",
		"component": "views/customer/list/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "客户列表",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 9200,
		"parentId": 9000,
		"children": [],
		"icon": "jh icon-jh-tianjialianxiren",
		"name": "新增客户",
		"spread": false,
		"path": "addCustomer",
		"component": "views/customer/add/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "新增客户",
		"sort": 2,
		"dataFlag": false
	}],
	"icon": "jh icon-jh-kehuguanli",
	"name": "客户管理",
	"spread": false,
	"path": "/cust",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "客户管理",
	"sort": 9,
	"dataFlag": false
}, {
	"id": 10000,
	"parentId": -1,
	"children": [{
		"id": 10100,
		"parentId": 10000,
		"children": [],
		"icon": "jh icon-jh-anliliebiao ",
		"name": "案例列表",
		"spread": false,
		"path": "page",
		"component": "views/sample-library/sample/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "案例列表",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 10200,
		"parentId": 10000,
		"children": [],
		"icon": "jh icon-jh-xinzenganli",
		"name": "新增案例",
		"spread": false,
		"path": "addCaseStore",
		"component": "views/sample-library/add/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "新增案例",
		"sort": 2,
		"dataFlag": false
	}],
	"icon": "jh icon-jh-anliku",
	"name": "案例库",
	"spread": false,
	"path": "/casestore",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "案例库",
	"sort": 10,
	"dataFlag": false
}, {
	"id": 11000,
	"parentId": -1,
	"children": [{
		"id": 11100,
		"parentId": 11000,
		"children": [],
		"icon": "jh icon-jh-xiangmuxinxi",
		"name": "项目列表",
		"spread": false,
		"path": "page",
		"component": "views/project/list/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "项目列表",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 11300,
		"parentId": 11000,
		"children": [],
		"icon": "jh icon-jh-xinzenganli",
		"name": "新增项目",
		"spread": false,
		"path": "addCustomerProject",
		"component": "views/project/add/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "新增项目",
		"sort": 3,
		"dataFlag": false
	}],
	"icon": "jh icon-jh-xiangmuguanli",
	"name": "项目管理",
	"spread": false,
	"path": "/proeject",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "项目管理",
	"sort": 11,
	"dataFlag": false
}, {
	"id": 12000,
	"parentId": -1,
	"children": [{
		"id": 12100,
		"parentId": 12000,
		"children": [],
		"icon": "jh icon-jh-shipinguanli",
		"name": "提案列表",
		"spread": false,
		"path": "page",
		"component": "views/video/list/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "提案列表",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 12200,
		"parentId": 12000,
		"children": [],
		"icon": "jh icon-jh-shipinxinzeng",
		"name": "新增提案",
		"spread": false,
		"path": "addCustomerProject",
		"component": "views/video/add/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "新增提案",
		"sort": 3,
		"dataFlag": false
	}],
	"icon": "jh icon-jh-shipintian",
	"name": "视频提案",
	"spread": false,
	"path": "/videoProposal",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "视频提案",
	"sort": 12,
	"dataFlag": false
}, {
	"id": 13000,
	"parentId": -1,
	"children": [{
		"id": 13100,
		"parentId": 13000,
		"children": [],
		"icon": "jh icon-jh-hetongliebiao",
		"name": "合同列表",
		"spread": false,
		"path": "page",
		"component": "views/contract/list/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "合同列表",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 13200,
		"parentId": 13000,
		"children": [],
		"icon": "jh icon-jh-hetongxinzeng",
		"name": "新增合同",
		"spread": false,
		"path": "add",
		"component": "views/contract/add/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "新增合同",
		"sort": 2,
		"dataFlag": false
	}, {
		"id": 13300,
		"parentId": 13000,
		"children": [],
		"icon": "jh icon-jh-hetongliucheng",
		"name": "流程管理",
		"spread": false,
		"path": "process/types",
		"component": "views/contract/process-management/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "流程管理",
		"sort": 3,
		"dataFlag": true
	}],
	"icon": " jh icon-jh-hetongguanli",
	"name": "合同管理",
	"spread": false,
	"path": "/contract",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "合同管理",
	"sort": 13,
	"dataFlag": false
}, {
	"id": 14000,
	"parentId": -1,
	"children": [{
		"id": 14100,
		"parentId": 14000,
		"children": [],
		"icon": "jh icon-jh-caiwuliebiao",
		"name": "财务",
		"spread": false,
		"path": "page",
		"component": "views/finance/list/index",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "财务",
		"sort": 1,
		"dataFlag": true
	}, {
		"id": 14200,
		"parentId": 14000,
		"children": [{
			"id": 14210,
			"parentId": 14200,
			"children": [],
			"icon": "",
			"name": "新增回款计划",
			"spread": false,
			"path": "plan",
			"component": "views/finance/add/plan/index",
			"authority": null,
			"redirect": null,
			"keepAlive": "0",
			"code": null,
			"type": "0",
			"label": "新增回款计划",
			"sort": 1,
			"dataFlag": false
		}, {
			"id": 14220,
			"parentId": 14200,
			"children": [],
			"icon": "",
			"name": "新增回款记录",
			"spread": false,
			"path": "record",
			"component": "views/finance/add/record/index",
			"authority": null,
			"redirect": null,
			"keepAlive": "0",
			"code": null,
			"type": "0",
			"label": "新增回款记录",
			"sort": 1,
			"dataFlag": false
		}],
		"icon": "jh icon-jh-caiwuxinzeng",
		"name": "新增",
		"spread": false,
		"path": "add",
		"component": "Layout",
		"authority": null,
		"redirect": null,
		"keepAlive": "0",
		"code": null,
		"type": "0",
		"label": "新增",
		"sort": 2,
		"dataFlag": false
	}],
	"icon": "jh icon-jh-caiwu",
	"name": "财务管理",
	"spread": false,
	"path": "/finance",
	"component": "Layout",
	"authority": null,
	"redirect": null,
	"keepAlive": "0",
	"code": null,
	"type": "0",
	"label": "财务管理",
	"sort": 14,
	"dataFlag": false
}];

function handleMenuPathParams(dataList) {
	return new Promise((resolve, reject) => {
		dataList.forEach(element => {
			const children = element.children || [];
			children.forEach(celement => {
				celement.path = `${element.path}/${celement.path}`;
				const cchildren = celement.children || [];
				cchildren.forEach(ccelement => {
					ccelement.path = `${element.path}/${celement.path}/${ccelement.path}`;
				});
			});
		});
		dataList.unshift({
			"icon": "iconfont iconxitongshouye",
			"name": "系统首页",
			"spread": false,
			"path": "/",
			"component": "Layout",
			"authority": null,
			"redirect": null,
			"keepAlive": "0",
			"code": null,
			"type": "0",
			"label": "系统首页",
			"sort": 14,
			"dataFlag": false
		});
		resolve(dataList);
	});
}

import {getPromiseButtonList} from "@api/common";

const state = {
	menu_info: [],
	promise_button_list: [],
};

const mutations = {
	SET_MENU_INFO: (state, menu_list) => {
		state.menu_info = menu_list;
	},
	SET_PROMISE_BUTTON_LIST: (state, promise_button_list) => {
		state.promise_button_list = promise_button_list;
	},
};


const actions = {
	GetMenu({commit}) {
		handleMenuPathParams(mockMenuData).then(data => {
			commit("SET_MENU_INFO", data);
		});
	},
	GetPromiseButtonList({commit}, token) {
		getPromiseButtonList(token).then(data => {
			commit("SET_PROMISE_BUTTON_LIST", data);
		});
	}
};



export default {
	state,
	actions,
	mutations,
};